class UserAlreadyExistsError(Exception):
    pass

class DatabaseError(Exception):
    pass